import Head from "next/head"
import { useRef } from "react"

interface Props {
    children: React.ReactNode
}

export default function PageWrapper({children}: Props){
    const rootRef = useRef<HTMLDivElement>(null!)

    return (
        <>
            <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='h-[100vh]' ref={rootRef}>
                <div className='h-[100%] w-full flex gap-widget p-widget'>
                    {children}
                </div>
            </div>
        </>
    )
}